# frozen_string_literal: true

module Engine
  module Game
    module G1835
      module Entities
        COMPANIES = [
          {
            name: 'Nürnberg-Fürth',
            sym: 'NF',
            value: 100,
            revenue: 5,
            desc: 'Nürnberg-Fürth Bahn, Director of AG may lay token on L14 north or south',
            abilities: [{ type: 'shares', shares: 'BY_2' }, {
              type: 'token',
              when: 'owning_player_track',
              description: 'desc NF',
              owner_type: 'player',
              hexes: ['L14'],
              price: 0,
              teleport_price: 0,
              count: 1,
              extra_action: true,
              from_owner: true,
            }],
            color: :turquoise,
            auction_row: 0,
          },
          {
            name: '1',
            sym: '1',
            value: 80,
            revenue: 0,
            desc:'',
            auction_row: 1
          },
          {
            name: 'Leipzig-Dresdner Bahn',
            sym: 'LD',
            value: 190,
            revenue: 20,
            desc: 'Leipzig-Dresdner Bahn - Sachsen Direktor Papier',
            abilities: [{ type: 'shares', shares: 'SX_0' },
                        { type: 'no_buy' },
                        { type: 'close', when: 'bought_train', corporation: 'SX' }],
            color: :red,
            auction_row: 1,
          },
          {
            name: '2',
            sym: '2',
            value: 170,
            revenue: 0,
            desc:'',
            auction_row: 1,
          },
          {
            name: '3',
            sym: '3',
            value: 80,
            revenue: 0,
            desc:'',
            auction_row: 2,
          },
          {
            name: '4',
            sym: '4',
            value: 160,
            revenue: 0,
            desc:'',
            auction_row: 2,
          },
          {
            name: 'Bayern Director',
            sym: "BY_D",
            value: 184,
            revenue: 0,
            desc: '',
            abilities: [
              {
                type: 'shares',
                shares: 'BY_0'
              }
            ],
            auction_row: 2,
          },
          {
            name: 'Braunschweigische Bahn',
            sym: 'BB',
            value: 130,
            revenue: 25,
            desc: 'Can be exchanged for a 10% share of Preussische Bahn',
            abilities: [
              {
                type: 'exchange',
                corporations: %w[PR_2],
                owner_type: 'player',
                when: ['Phase 2.3', 'Phase 2.4', 'Phase 3.1'],
                from: 'ipo',
              },
            ],
            color: :oegray,
            auction_row: 2,
          },
          {
            name: 'Hannoversche Bahn',
            sym: 'HB',
            value: 160,
            revenue: 30,
            desc: '10 Percent Share of Preussische Bahn on Exchange',
            abilities: [
              {
                type: 'exchange',
                corporations: %w[PR_1],
                owner_type: 'player',
                when: ['Phase 2.3', 'Phase 2.4', 'Phase 3.1'],
                # reserved papers perhaps a option
                from: 'ipo',
              },
            ],
            color: :oegray,
            auction_row: 3,
          },
          {
            name: '5',
            sym: '5',
            value: 80,
            revenue: 0,
            desc:'',
            auction_row: 3,
          },
          {
            name: '6',
            sym: '6',
            value: 80,
            revenue: 0,
            desc:'',
            auction_row: 3,
          },
          {
            name: 'Ostbayrische Bahn',
            sym: 'OBB',
            value: 120,
            revenue: 10,
            desc: 'Ostbayrische Bahn - 2 Tiles on M15, M17 extra (one per OR) and without cost',
            abilities: [
              {
                type: 'tile_lay',
                description: "Place a free track tile at M15, M17 at any time during the corporation's operations.",
                owner_type: 'player',
                hexes: %w[M15 M17],
                tiles: %w[3 4 7 8 9 58],
                free_tile_lay: true,
                when: 'owning_player_track',
                count: 2,
                connect: false
              },
              { type: 'shares', shares: 'BY_1' },
            ],
            color: :turquoise,
            auction_row: 3,
          },
          {
            name: 'Pfalzbahnen',
            sym: 'PB',
            value: 150,
            revenue: 15,
            desc: 'Can lay a tile on L6 and Token on L6 if Baden AG is active already',
            abilities: [
              {
                type: 'tile_lay',
                description: 'desc: Pfalzbahnen lay',
                owner_type: 'player',
                free_tile_lay: true,
                hexes: ['L6'],
                when: 'owning_player_track',
                tiles: %w[210 211 212 213 214 215],
              },
              { type: 'shares', shares: 'BY_3' },
              {
                type: 'token',
                description: 'desc: Pfalzbahnen token',
                when: 'owning_player_track',
                owner_type: 'corporation',
                hexes: ['L6'],
                city: 3,
                price: 0,
                teleport_price: 0,
                count: 1,
                extra_action: true,
              },
            ],
            color: :turquoise,
            auction_row: 3,
          },
        ].freeze

        CORPORATIONS = [
          {
            sym: 'BY',
            name: 'Bayrische Eisenbahn',
            type: 'major',
            logo: '1835/BY',
            simple_logo: '1835/BY.alt',
            tokens: [0, 0, 0, 0, 0],
            float_percent: 50,
            max_ownership_percent: 100,
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            coordinates: 'O15',
            color: :turquoise,
          },
          {
            sym: 'SX',
            name: 'Sächsische Eisenbahn',
            type: 'major',
            logo: '1835/SX',
            simple_logo: '1835/SX.alt',
            tokens: [0, 0, 0],
            float_percent: 50,
            max_ownership_percent: 100,
            shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
            coordinates: 'H16',
            color: '#d81e3e',
          },
          {
            sym: 'BA',
            name: 'Badische Eisenbahn',
            type: 'major',
            logo: '1835/BA',
            simple_logo: '1835/BA.alt',
            tokens: [0, 0],
            float_percent: 50,
            max_ownership_percent: 100,
            shares: [20, 10, 10, 10, 10, 10, 10, 20],
            coordinates: 'L6',
            color: '#7b352a',
          },
          {
            sym: 'WT',
            name: 'Württembergische Eisenbahn',
            type: 'major',
            logo: '1835/WT',
            simple_logo: '1835/WT.alt',
            tokens: [0, 0],
            float_percent: 50,
            max_ownership_percent: 100,
            shares: [20, 10, 10, 10, 10, 10, 10, 20],
            coordinates: 'M9',
            color: :yellow,
          },
          {
            sym: 'HE',
            name: 'Hessische Eisenbahn',
            type: 'major',
            logo: '1835/HE',
            simple_logo: '1835/HE.alt',
            tokens: [0, 0],
            float_percent: 50,
            max_ownership_percent: 100,
            shares: [20, 10, 10, 10, 10, 10, 10, 20],
            coordinates: 'J8',
            color: :green,
          },
          {
            sym: 'MS',
            name: 'Eisenbahn Mecklenburg Schwerin',
            type: 'major',
            logo: '1835/MS',
            simple_logo: '1835/MS.alt',
            tokens: [0, 0],
            percent: 10,
            float_percent: 60,
            max_ownership_percent: 100,
            shares: [20, 20, 20, 10, 10, 10, 10],
            price_percent: 20,
            forced_share_percent: 10,
            fraction_shares: false,
            coordinates: 'C13',
            color: :violet,
          },
          {
            sym: 'OL',
            name: 'Oldenburgische Eisenbahn',
            type: 'major',
            logo: '1835/OL',
            simple_logo: '1835/OL.alt',
            tokens: [0, 0],
            percent: 10,
            float_percent: 60,
            max_ownership_percent: 100,
            shares: [20, 20, 20, 10, 10, 10, 10],
            price_percent: 20,
            forced_share_percent: 10,
            fraction_shares: false,
            coordinates: 'D6',
            color: '#6e6966',
          },
          {
            sym: 'PR',
            name: 'Preußische Eisenbahn',
            type: 'major',
            logo: '1835/PR',
            simple_logo: '1835/PR.alt',
            tokens: [0, 0, 0, 0, 0],
            floatable: false,
            max_ownership_percent: 100,
            shares: [10, 10, 10, 10, 10, 10, 10, 10, 5, 5, 5, 5],
            # shares for minors and Privates should be reserved
            # coordinates: 'E19',
            color: '#37383a',
          },
          {
            sym: '1',
            name: 'Bergisch Märkische Bahn',
            logo: '1835/P1',
            simple_logo: '1835/PR.alt',
            tokens: [0],
            type: 'minor',
            shares: [100],
            hide_shares: true,
            float_percent: 100,
            # abilities: [
            #   {
            #     type: 'exchange',
            #     corporations: %w[PR_9],
            #     owner_type: 'player',
            #     when: ['Phase 2.3', 'Phase 2.4', 'Phase 3.1'],
            #     # reserved papers perhaps a option
            #     from: 'ipo',
            #   },
            # ],
            coordinates: 'H2',
            color: '#37383a',
          },
        # ]
        # foo = [
          {
            sym: '2',
            name: 'Berlin Potsdamer Bahn',
            logo: '1835/P2',
            simple_logo: '1835/PR.alt',
            tokens: [0],
            type: 'minor',
            shares: [100],
            hide_shares: true,
            float_percent: 100,
            # abilities: [
            #   {
            #     type: 'exchange',
            #     corporations: %w[PR_0x],
            #     owner_type: 'player',
            #     when: ['Phase 2.3', 'Phase 2.4', 'Phase 3.1'],
            #     # reserved papers perhaps a option
            #     from: 'ipo',
            #   },
            # ],
            coordinates: 'E19',
            city: 0,
            color: '#37383a',
          },
          {
            sym: '3',
            name: 'Magdeburger-Bahn',
            logo: '1835/P3',
            simple_logo: '1835/PR.alt',
            tokens: [0],
            type: 'minor',
            shares: [100],
            hide_shares: true,
            float_percent: 100,
            # abilities: [
            #   {
            #     type: 'exchange',
            #     corporations: %w[PR_10],
            #     owner_type: 'player',
            #     when: ['Phase 2.3', 'Phase 2.4', 'Phase 3.1'],
            #     # reserved papers perhaps a option
            #     from: 'ipo',
            #   },
            # ],
            coordinates: 'F14',
            color: '#37383a',
          },
          {
            sym: '4',
            name: 'Köln-Mindener Bahn',
            logo: '1835/P4',
            simple_logo: '1835/PR.alt',
            tokens: [0],
            type: 'minor',
            shares: [100],
            hide_shares: true,
            float_percent: 100,
            # abilities: [
            #   {
            #     type: 'exchange',
            #     corporations: %w[PR_3],
            #     owner_type: 'player',
            #     when: ['Phase 2.3', 'Phase 2.4', 'Phase 3.1'],
            #     # reserved papers perhaps a option
            #     from: 'ipo',
            #   },
            # ],
            coordinates: 'G5',
            color: '#37383a',
          },
          {
            sym: '5',
            name: 'Berlin Stettiner Bahn',
            logo: '1835/P5',
            simple_logo: '1835/PR.alt',
            tokens: [0],
            type: 'minor',
            shares: [100],
            hide_shares: true,
            float_percent: 100,
            # abilities: [
            #   {
            #     type: 'exchange',
            #     corporations: %w[PR_11],
            #     owner_type: 'player',
            #     when: ['Phase 2.3', 'Phase 2.4', 'Phase 3.1'],
            #     # reserved papers perhaps a option
            #     from: 'ipo',
            #   },
            # ],
            coordinates: 'E19',
            city: 1,
            color: '#37383a',
          },
          {
            sym: '6',
            name: 'Altona Kiel Bahn',
            logo: '1835/P6',
            simple_logo: '1835/PR.alt',
            tokens: [0],
            type: 'minor',
            shares: [100],
            hide_shares: true,
            float_percent: 100,
            # abilities: [
            #   {
            #     type: 'exchange',
            #     corporations: %w[PR_12],
            #     owner_type: 'player',
            #     when: ['Phase 2.3', 'Phase 2.4', 'Phase 3.1'],
            #     # reserved papers perhaps a option
            #     from: 'ipo',
            #   },
            # ],
            coordinates: 'C11',
            city: 1,
            color: '#37383a',
          },
        ].freeze
      end
    end
  end
end
